application/views/donante/registrarDonante.php, application/views/templates/pie.php
=> modif reg donante y pie

application/controllers/Cfrascos.php
=> controller frascos

application/models/Frascos_model.php
=> modelo frasco

application/controllers/Cfrascos.php, application/models/Frascos_model.php, application/views/hojaruta/editarUnaHojaRuta.php, application/views/hojaruta/verTodashr.php, application/views/hojaruta/verUnaHojaRuta.php, application/views/hojaruta/verhrSemanal.php, application/views/templates/pie.php
boton volver en HR y modelo - controlador de Frascos
=> boton volver en HR y modelo - controlador de Frascos

application/config/autoload.php, application/views/hojaruta/generarHrCons.php
boton volver en generarHRCons y agregue model de frasco en autoload
=> boton volver en generarHRCons y agregue model de frasco en autoload

application/views/bebe/bebeAsociado.php, application/views/bebe/bebeAsociado_cons.php, application/views/bebe/verUnBebeAsociado.php, application/views/consentimiento/buscaconsentimiento.php, application/views/consentimiento/consentimiento2.php, application/views/consentimiento/verConsentimientos.php, application/views/consentimiento/verUnConsentimiento.php, application/views/donante/editarDonante.php, application/views/donante/registrarDonante.php, application/views/donante/verUnaDonante.php, application/views/donante/verUnaDonante_cons.php, application/views/seguimiento/seguimientoBR.php, application/views/seguimiento/seguimientoBa.php, application/views/seguimiento/seguimientoBa1.php, application/views/seguimiento/verSeguimientoBa.php, application/views/serologia/registrarSerologia.php
=> lo que cambio elisa

application/controllers/Cfrascos.php, application/views/frascos/ingresoFrascos.php, application/views/frascos/verFrascos.php, application/views/templates/menu.php
=> lo q hoce hasta ahora

application/controllers/Cfrascos.php, application/models/Frascos_model.php, application/views/frascos/ingresoFrascos.php, application/views/frascos/sintitulo, application/views/serologia/registrarSerologia.php, application/views/serologia/verSerologias.php, application/views/serologia/verTodasSerologias.php
hay algo de serologia que agregue. controlale con el trello. si le falta algo
=> algo nuevo de frascos

application/config/database.php, application/controllers/Cfrascos.php, application/models/Consentimiento_model.php, application/views/frascos/ingresoFrascos.php, application/views/frascos/verFrascos.php, application/views/templates/pie.php, assets/internals/js/frascosinfo.js
=> avance un poco de frasco

application/controllers/Cfrascos.php, application/models/Frascos_model.php, application/views/frascos/verFrascos.php, application/views/frascos/verUnFrasco.php
un poquito mas de avance en frasco
=> un poquito mas de avance

application/controllers/Cfrascos.php, application/views/frascos/registrarAnalisisFrasco.php
actualizacion cinco de la tarde
=> actualizacion cinco de la tarde

application/config/database.php, application/controllers/Cfrascos.php, application/models/Bebeasociado_model.php, application/views/frascos/editarFrasco.php, application/views/frascos/registrarAnalisisFrasco.php, application/views/frascos/verFrascos.php, assets/internals/js/frascosinfo.js
actualizacion a las once menos cuarto
=> actualizacion a las once menos cuarto

application/controllers/Cfrascos.php, application/models/Frascos_model.php, application/views/bebe/verUnBebeAsociado.php, application/views/consentimiento/editarConsentimiento.php, application/views/consentimiento/finConsentimiento.php, application/views/consentimiento/verConsentimientos.php, application/views/consentimiento/verUnConsentimiento.php, application/views/frascos/verFrascos.php, application/views/frascos/verFrascosPorDonante.php, application/views/seguimiento/seguimientoBa1.php, application/views/seguimiento/seguimientosUnBa.php, application/views/seguimiento/verUnSeguimBa.php, application/views/serologia/verTodasSerologias.php, application/views/serologia/verUnaSerologia.php, application/views/templates/menu.php
actualizacion a las dos y media
=> actualizacion a las dos y media

application/views/bebe/verUnBebeAsociado.php, application/views/consentimiento/editarConsentimiento.php, application/views/consentimiento/verUnConsentimiento.php, application/views/donante/donante_en_consentimiento.php, application/views/donante/verUnaDonante.php, application/views/donante/verUnaDonante_cons.php, application/views/frascos/editarFrasco.php, application/views/frascos/registrarAnalisisFrasco.php, application/views/frascos/verUnFrasco.php, application/views/hojaruta/agregarConsentimientos.php, application/views/hojaruta/editarUnaHojaRuta.php, application/views/hojaruta/generarHrCons.php, application/views/hojaruta/quitarConsentimientos.php, application/views/hojaruta/registrarIngresoHr.php, application/views/hojaruta/verTodashr.php, application/views/hojaruta/verUnaHojaRuta.php, application/views/hojaruta/verhrSemanal.php, application/views/seguimiento/seguimientoBa1.php, application/views/seguimiento/verUnSeguimBa.php, application/views/serologia/verTodasSerologias.php, application/views/serologia/verUnaSerologia.php, application/views/zona/altaZona.php, application/views/zona/editarZona.php, application/views/zona/eliminarZona.php, application/views/zona/verUnaZona.php
=> modificaciones lunes 30

application/views/donante/editarDonante.php, application/views/seguimiento/seguimientosUnBa.php, reporte2.php
modifique vista editar donante
=> modifique editar donante

application/controllers/Cfrascos.php, application/views/bebe/editarUnBebeAsociado.php, application/views/bebe/verBebeasociado.php, application/views/consentimiento/verTodosConsentimientos.php, application/views/frascos/bajaFrasco.php, application/views/frascos/verFrascos.php, application/views/templates/menu.php
=> baja de frascos hecha

application/controllers/Cbebe.php, application/views/bebe/editarUnBebeAsociado.php
lo arregle porque no guardaba.
=> arregle editar bebe asociado

application/views/frascos/bajaFrasco.php, application/views/frascos/verFrascos.php
agregue lista de rechazo de frasco
=> modif frasco

application/controllers/CentrosRec.php, application/models/Centros_model.php, application/views/centros/registrarCentrosR.php, application/views/centros/verCentrosR.php, assets/internals/js/centrosinfo.js
=> centros de recoleccion

application/views/bebe/editarUnBebeReceptor.php
=> bebe receptor

application/controllers/Cseguimiento.php, application/models/SeguimientoBr_model.php, application/views/seguimiento/editarUnSegBr.php, application/views/seguimiento/seguimientoBr1.php, application/views/seguimiento/seguimientosUnBa.php, application/views/seguimiento/seguimientosUnBr.php, application/views/seguimiento/verSeguimientoBr.php, application/views/seguimiento/verUnSeguimBr.php, assets/internals/js/seguimientobr.js
=> bebes y seguimientos terminados

application/controllers/CentrosRec.php, application/models/Centros_model.php, application/views/centros/editarCentroR.php, application/views/centros/eliminarCentro.php, application/views/centros/registrarCentrosR.php, application/views/centros/verCentrosR.php
no funca el borrar, no se porque
=> centro de recoleccion

application/models/Centros_model.php
=> eliminar centro

application/views/bebe/bebeReceptor.php
=> Bancoelisa

application/controllers/Cfraccionamiento.php, application/models/Fraccionamiento_model.php, application/views/bebe/bebeReceptor.php, application/views/fraccionamiento/registrarConsumoBr.php, application/views/fraccionamiento/verFraccionesUnbr.php, application/views/pasteurizacion/cargaCultivoBiberon.php, application/views/templates/menu.php
no me busca los fraccionamientos del bebe el model esta bien, yo lo soluciono por ahora paso esto si queres y podes fijate, le puedo estar pifiando en el pase de parametros
=> fraccionamiento provisorio

application/controllers/Cfraccionamiento.php, application/views/fraccionamiento/registrarConsumoBr.php, application/views/fraccionamiento/verFraccionesUnbr.php, assets/internals/js/consentimientoinfo.js
=> lo de la mañana

application/views/frascos/ingresoFrascos.php, application/views/pasteurizacion/nuevaPasteurizacion.php, application/views/templates/menu.php
nuevaPasteurizacion, agregue al menu el acceso y cambie algo de controlador de pasteurizacion :-P
=> pasteurizacion

application/controllers/Cfraccionamiento.php, application/views/fraccionamiento/verFraccionesUnbr.php, application/views/fraccionamiento/verTodosLosFraccionamientos.php
En el ver todos los fraccionamientos puse que muestre si o no en consumo. Sólo eso.
En el controlador hice el proyecto de consulta para el arreglo de consumo que necesito, pero me perdi en el camino y ya es medio tarde, envío porque quizás sirva.
En la vista consumosUnBeber sólo cambie el name de consumo.
=> proyecto de consulta

application/controllers/Cpasteurizacion.php, application/models/Frascos_model.php, application/models/Pasteurizacion_model.php, application/views/pasteurizacion/mostrarFrascos.php
=> mas sobre pasteurizacion

application/controllers/Cpasteurizacion.php, application/views/pasteurizacion/mostrarFrascos.php, application/views/pasteurizacion/nuevaPasteurizacion.php, assets/internals/js/pasteurizacioninfo.js
=> mostrar frascos a pasteurizar

application/controllers/Cfraccionamiento.php, application/models/Fraccionamiento_model.php, application/views/fraccionamiento/verFraccionesUnbr.php
avisame cuando puedo tocaro te pregunto.
mientras armo la vista del login
=> ordene un poco la funcion pero todavia no esta

application/controllers/Cpasteurizacion.php, application/models/Pasteurizacion_model.php, application/views/pasteurizacion/inicioPasteurizacion.php, application/views/pasteurizacion/nuevaPasteurizacion.php, assets/internals/js/pasteurizacioninfo.js
insertar una pasteurizacion en la tabla Pateurizacion!!
=> registrar una pasteurizacion en su tabla

application/controllers/Cpasteurizacion.php, application/views/pasteurizacion/inicioPasteurizacion.php, application/views/templates/menu.php, application/views/welcome_message.php
unas cosillas mas en la vista de inicio pasteurizacion
=> unas cosillas mas en la vista de inicio pasteurizacion

application/views/pasteurizacion/nuevaPasteurizacion.php
=> cambios en pasteu

application/controllers/Cpasteurizacion.php, application/views/pasteurizacion/nuevaPasteurizacion.php, application/views/pasteurizacion/otraForma.php, assets/internals/js/pasteurizacioninfo.js
=> otra forma de pasteurizacion

application/controllers/Cpasteurizacion.php, application/views/pasteurizacion/nuevaPasteurizacion.php, application/views/pasteurizacion/otraForma.php
=> algo mas de pasteurizacion

application/controllers/Cbiberon.php, application/models/Biberon_model.php, application/views/biberones/cargaCultivoBiberon.php, application/views/reportes/repor_donante.php, assets/internals/js/biberoninfo.js
=> carga de analisis del biberon lista 

application/views/biberones/editarBiberon.php, application/views/biberones/verUnBiberon.php
un toque nomas le faltsa, mando porque tengo bajones de tension por las dudas prevengo
=> ver listo y andando, editar listo no andando

application/controllers/CciSessions2.php, application/controllers/Cpasteurizacion.php, application/models/Biberon_model.php, application/models/ciSessions2_model.php
controlador y modelo de cisessions2. 
Algo mas de pasteurizacion
=> controlador y modelo de cisessions2. Algo mas de pasteurizacion

application/controllers/Cserologia.php, application/views/serologia/editarSerologia.php, application/views/serologia/verSerologias.php, application/views/serologia/verTodasSerologias.php
=> casi editar serologia

application/controllers/Cpasteurizacion.php
=> pasteuriza 35 biberones ahora

application/controllers/Cserologia.php
Listo serología. Método que controla estado de serología en el controlador.
=> Listo serologia

application/controllers/Cpasteurizacion.php, application/models/Biberon_model.php, application/models/Frascos_model.php, application/views/frascos/bajaFrasco.php, application/views/frascos/editarFrasco.php, application/views/frascos/registrarAnalisisFrasco.php, application/views/frascos/verUnFrasco.php, application/views/pasteurizacion/inicioPasteurizacion.php, application/views/pasteurizacion/nuevaPasteurizacion.php, application/views/pasteurizacion/otraForma.php, application/views/pasteurizacion/verPasteurizaciones.php, application/views/templates/pie.php
pasteurizacion retorques, frascos retoques y algo de pie
=> pasteurizacion retorques, frascos retoques y algo de pie

application/controllers/Cpasteurizacion.php
=> pasteurizaion

application/controllers/Cpasteurizacion.php, application/views/pasteurizacion/bajaPasteurizacion.php, application/views/pasteurizacion/inicioPasteurizacion.php, application/views/pasteurizacion/mostrarPasteurizacion.php, application/views/pasteurizacion/otraForma.php, assets/internals/js/pasteurizacioninfo.js
=> baja pasteurizacion

application/controllers/Cfrascos.php, application/models/Frascos_model.php, application/views/frascos/ingresoFrascos.php, application/views/frascos/registrarAnalisisFrasco.php, application/views/frascos/verFrascosPasteurizados.php, application/views/hojaruta/editarUnaHojaRuta.php, application/views/hojaruta/verTodashr.php, application/views/hojaruta/verhrSemanal.php, application/views/pasteurizacion/editarPasteurizacion.php, application/views/pasteurizacion/inicioPasteurizacion.php, application/views/pasteurizacion/mostrarPasteurizacion.php, application/views/pasteurizacion/verPasteurizaciones.php, application/views/pasteurizacion/verUnaPasteurizacion.php
correcciones en frasco, pasteurizacion y hoja de ruta
=> correcciones en frasco, pasteurizacion y hoja de reuta

application/controllers/Consentimiento.php, application/views/bebe/bebeAsociado_cons.php, application/views/bebe/verBebereceptor.php, application/views/centros/verCentrosR.php, application/views/consentimiento/consentimiento2.php, application/views/consentimiento/editarConsentimiento.php, application/views/consentimiento/finConsentimiento.php, application/views/consentimiento/verConsentimientos.php, application/views/consentimiento/verTodosConsentimientos.php, application/views/consentimiento/verUnConsentimiento.php, application/views/templates/menu.php
=> listo consentimiento, menu tentativo y un par de vistas mas

application/controllers/Cfrascos.php, application/views/frascos/registrarAnalisisFrasco.php
correcciones de frasco numero 1243242423543543
=> correcciones de frasco numero 1243242423543543

application/controllers/Cfrascos.php, application/models/Frascos_model.php, application/views/frascos/editarFrasco.php, application/views/frascos/registrarAnalisisFrasco.php, application/views/frascos/verFrascos.php
correccion en frasco un vez mas
=> correccion en frasco un vez mas
